### ISSUE TITLE
There are no ICC profiles

### ISSUE THREAD

**Issue by alexb3d** [flathub/org.kde.krita#5] opened 2018-05-17 16:06 UTC
Krita can not access the predefined ICC profile path "/usr/share/color/icc".
The same goes for Gimp, Inkscape, Darktable, etc. But Blender of Flatpak if you can access the ICC profiles.

[Blender](https://yadi.sk/i/4XxhosH_3W5giQ)

**Comment by eszlari** [comment] 2018-05-17 16:40
Since other apps are affected, maybe file an issue under https://github.com/flathub/flathub/issues, so some of the flatpak developers see it?!

**Comment by alexb3d** [comment] 2018-05-17 17:01
They are already notified but they closed the post.
https://github.com/flatpak/flatpak/issues/1660#issuecomment-387805640

Gimp access all the profiles here "/run/host/usr/share/color/icc/"
https://github.com/flathub/org.gimp.GIMP/issues/15#issuecomment-389929536

Darktable You have to copy manually here /home/user/.var/app/org.darktable.Darktable/config/darktable/color/out
https://github.com/flathub/org.darktable.Darktable/issues/16#issuecomment-389923502

**Comment by eszlari** [comment] 2018-08-13 15:54
https://bugs.kde.org/show_bug.cgi?id=397423

**Comment by eszlari** [comment] 2018-08-13 19:07
@alexb3d Could you describe the expected behavior again in detail?

**Comment by alexb3d** [comment] 2018-08-13 23:38
Hi @eszlari . This is already solved.

Krita (Flatpak) can not access `/usr/share/color/icc` to apply the ICC color profiles.
The new path is `/run/host/usr/share/color/icc/`

**Comment by eszlari** [comment] 2018-08-14 12:55
> Hi @eszlari . This is already solved.

If it is solved, why don't you close the issue?

> Krita (Flatpak) can not access /usr/share/color/icc to apply the ICC color profiles.
The new path is /run/host/usr/share/color/icc/

Have you tested this recently? If I delete `.var/app/org.kde.krita`, start Krita and then go to the color management preferences, the open file dialog brings me right to `/usr/share/color/icc`.

**Comment by alexb3d** [comment] 2018-08-18 22:00
> If it is solved, why don't you close the issue?
I have no idea.

> Have you tested this recently? If I delete .var/app/org.kde.krita, start Krita and then go to the color management preferences, the open file dialog brings me right to /usr/share/color/icc.
No, open in Home as always.

There is a confusion, several actually. I do not understand why there are github and bugs.kde, this confuses me ...

The original problem was that Krita (Flatpak) does not have access to the ICC profiles `/usr/share/color/icc`. To calibrate my Hardware and my Software I need to have access to the profiles. This is understood, I suppose.

Krita has no problem. Flatpak has no problem.

The problem is "communicational". It took me a long time to learn that Flatpak accesses the profiles in this directory  `/run/host/usr/share/color/icc/`.

**Comment by eszlari** [comment] 2018-08-19 03:39
> I do not understand why there are github and bugs.kde, this confuses me ...

This bug tracker here on Github is for flatpak specific bugs and https://bugs.kde.org is the official Krita upstream bug tracker.

**Closed by eszlari** 2018-08-19 03:39 UTC
