### ISSUE TITLE
Update runtime to 5.14

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/org.kde.krita#16] opened 2019-09-19 20:47 UTC

**Comment by boudewijnrempt** [comment] 2019-09-20 06:37
That would be fairly dangerous: Qt 5.13 has a bug in the regular expression engine that makes Krita crash on exit.

**Comment by eszlari** [comment] 2019-09-20 10:29
> That would be fairly dangerous: Qt 5.13 has a bug in the regular expression engine that makes Krita crash on exit.

Thanks for the hint! Is this still true for 5.13.1?

**Comment by boudewijnrempt** [comment] 2019-09-20 17:39
According to our testers, yes. we haven't tried a 5.14 beta yet...

**Comment by eszlari** [comment] 2019-10-02 18:31
I couldn't find a bug report on https://bugreports.qt.io, is there one?

**Comment by boudewijnrempt** [comment] 2019-10-02 18:35
No, there isn't one. I haven't managed to make a minimal example, and without one, it's not useful to make a report. I did patch Krita today to work around the issue, but that patch is not in 4.2.7 which will be released tomorrow. See https://invent.kde.org/kde/krita/commit/ca07d42ca64271689f1a1ea2219b4909bd97f7c1 .

**Comment by eszlari** [comment] 2020-03-25 21:34
@boudewijnrempt Do you consider it safe to switch to Qt 5.14 with Krita 4.2.9?

**Comment by boudewijnrempt** [comment] 2020-04-10 14:13
Sorry for the late reply, I missed the notification. But, no... 5.14 has even worse bugs, for instance with PNG handling.

**Comment by eszlari** [comment] 2020-04-11 13:23
Thank you for the clarification!

The problem is: the 5.12 runtime still is based on the older 18.08 freedesktop runtime, while versions 5.13 and 5.14 are based on the newer and better maintained 19.08 freedesktop runtime. This problematic especially when it comes to hardware support:  18.08 is currently at Mesa version 19.1 (https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/18.08/NEWS), while 19.08 has Mesa 20.0 (https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/blob/19.08/NEWS). Additionally, with 19.08 they moved Mesa into a runtime extension (`org.freedesktop.Platform.GL.default`), which means other runtimes like the GNOME or KDE runtimes, can pick up Mesa updates, without needing to be rebuild.

**Comment by boudewijnrempt** [comment] 2020-04-11 14:35
You could test with 5.14, I guess... I did work around some of the worst problems, since my dev machine has 5.14.

**Closed** 2020-04-14 11:05 UTC
